# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-619z3.us-east1.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=SIZZ6XMJEAXYQQLV
sasl.password=inPaGQesimnAbdmoFSvTeyiajK0Rfh+o7UiZfVD0r3WNc3jRON3eF+Qgid+cN2W+

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-python-client-de9a26e4-3814-4796-8124-f90ebc97c483
